name: Flutter Nightly Build

on:
  workflow_dispatch:
    inputs:
      upload-tag:
        description: 'Tag for upload'
        required: true
        default: 'nightly'

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.event.inputs.upload-tag }}
